language: node_js
node_js:
- '4'
notifications:
  slack:
    secure: YmKEo9yQ5JVaaxcREFA2KtJd9AGa3JeU+YiSDrzw3ODgrPBIrI0WDZq8BX1XJ5GRXatxVs4aVnDYKamMWzniJ4d3U9iy2Hs1MqcGo2q4yNmRzX1PuUuLMyX1U3mC9HmWsCbz9M5a6yHk/OdVfl5N0NRZJ3xFYY0X/+Mt9B0ut9YLKHZOuSMEv/pjbwM9LhyOY3zk4w9svsxqjXm/0kzIpqi265BQb3LFQeYUSUbtEuAK0Z57C05Xuirm4nNfeHdLnwOz0szUvXryuDFUiZo+z14Hgh4wHA/zW5XvtTve48yEBlRT0PZhfZfnf3g0S1omgLoUYFHpiE7bLrGF4NwgZba7IabKg3Umydt+bs4HsbcgEi6fEjqrKzpR/0N8MkYxr9iC6dQ8s0yASi6teYj0UhkQx1CVPmpJ8bUdtRrkSwmNh5tQGBCOTVMpY+XayXNejruKRhBqXk5ejXAF7i83tyMi1ISsKkEwVbOk5rC+26Kuh0lu49zMIBJiZOxZqh9OtuUwhr/wK4K8E8E5wLg2JniHPMnTms4ecn6uvEo7pVdUHfp3ExrmUrC9fMQb/EeHOMrhBINefVXaayL57gOeaMaJo3d92LGf59TBpL88gQ45zbjxzQPc2cNRvcBcu9HJe9yi9E5b686z3r6kjbEjiA+4gvKgta57V8C5iWFU3g8=
